services:
  backend-app:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/frontend-app/
      dockerfile: Dockerfile
    ports:
      - "3000:4173"
    depends_on:
      - backend-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
